<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_LoadingCreate development store</name>
   <tag></tag>
   <elementGuidId>2f37d2d0-d7ee-4c8d-8ce3-72a0e7ac24b2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.Polaris-LegacyStack__Item</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//main[@id='AppFrameMain']/div/div/div[2]/form/div/div[2]/div/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>6ffd812e-3243-42d1-bf3f-099fe94db707</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Polaris-LegacyStack__Item</value>
      <webElementGuid>6818fe04-43d5-42a2-9c20-83406f9c8514</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>LoadingCreate development store</value>
      <webElementGuid>5a500a45-504e-461d-a452-c648977ec0d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;AppFrameMain&quot;)/div[@class=&quot;Polaris-Frame__Content&quot;]/div[@class=&quot;Polaris-Page&quot;]/div[@class=&quot;Polaris-Page--divider&quot;]/form[1]/div[@class=&quot;Polaris-Layout&quot;]/div[@class=&quot;Polaris-Layout__Section&quot;]/div[@class=&quot;Polaris-PageActions&quot;]/div[@class=&quot;Polaris-LegacyStack Polaris-LegacyStack--spacingTight Polaris-LegacyStack--distributionTrailing&quot;]/div[@class=&quot;Polaris-LegacyStack__Item&quot;]</value>
      <webElementGuid>3331896c-6cbd-409a-a219-775c91d30640</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='AppFrameMain']/div/div/div[2]/form/div/div[2]/div/div/div</value>
      <webElementGuid>2dc9cb90-9e0a-4f14-bf95-0482371937e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Learn more.'])[1]/following::div[4]</value>
      <webElementGuid>2717b805-8032-4ee6-87dd-e4da6dfc2ba3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div[2]/div/div/div</value>
      <webElementGuid>5b176dde-978c-433b-8aa2-b676a63acb3b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'LoadingCreate development store' or . = 'LoadingCreate development store')]</value>
      <webElementGuid>aa3692ec-752e-490e-913b-14c6c83912d8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
