<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Store Name_PolarisTextField3</name>
   <tag></tag>
   <elementGuidId>fb1467a3-ac23-45f8-b902-9c25d435d280</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#PolarisTextField3</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='PolarisTextField3']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>fb60992f-7b6b-482e-abd8-559dc0ec6007</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>PolarisTextField3</value>
      <webElementGuid>1b65d70b-b8ba-41ff-9acb-95741d0636bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>8a514623-af73-49b2-8ada-bd77f7f5221e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Polaris-TextField__Input</value>
      <webElementGuid>6329cf20-ed30-4f44-ad6d-f7681bb10406</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>cfdb99a2-1685-42db-a431-38324f6cd7ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>PolarisTextField3Label</value>
      <webElementGuid>4b121f31-9b50-41c8-8ade-dc813fb1b387</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>7cd24321-f5f0-41ca-b486-831ec764b448</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;PolarisTextField3&quot;)</value>
      <webElementGuid>13266839-9e40-4ec3-b30b-8fbed7fc3a96</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='PolarisTextField3']</value>
      <webElementGuid>99702850-baba-444f-8795-34b618dbbe0f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='AppFrameMain']/div/div/div[2]/form/div/div/div/div[2]/div/div/div/div[2]/div/div/input</value>
      <webElementGuid>780d6798-d6d4-4674-b76d-5a952c9f2e24</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div[2]/div/div/input</value>
      <webElementGuid>2c736289-a1fc-4ebc-bb21-d3d168a1c5ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'PolarisTextField3' and @type = 'text']</value>
      <webElementGuid>7afd486a-69d2-4e42-b2ae-742b5ab5f47e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
